"""
Unit tests for WeatherAgent + WeatherDataAdapter (issue #10, FR-WX-1..4).

Owner: P3. No network: the agent is tested against a fake adapter, and the
adapter is tested via its pure helpers + monkeypatched per-source fetchers.
The Open-Meteo / GDACS fixtures are the real payloads captured under
docs/samples/weather/ (regenerated by scripts/p3_sample_calls.sh).
"""
from __future__ import annotations

import json
import xml.etree.ElementTree as ET
from datetime import UTC, datetime
from pathlib import Path

import httpx
import pytest

from app.agents.weather_agent import WeatherAgent
from app.data_access import weather_adapter as wa
from app.data_access.base import AdapterResult
from app.data_access.weather_adapter import (
    _GDACS_NS,
    WeatherDataAdapter,
    _alert_strings,
    _gdacs_item_latlon,
    _normalise,
    _parse_gdacs_tc,
)
from app.schemas.common import LatLon

SAMPLES = Path(__file__).resolve().parents[3] / "docs" / "samples" / "weather"


def _json(name: str) -> dict:
    return json.loads((SAMPLES / name).read_text(encoding="utf-8"))


def _text(name: str) -> str:
    # Explicit encoding, not the platform default (#97): gdacs_tc_rss.xml is a
    # real captured payload with a leading UTF-8 BOM. A bare read_text() picks
    # up the OS locale encoding (cp1252 on Windows), which mis-decodes the BOM
    # into 3 garbage chars and breaks ET.fromstring. httpx (and every other
    # UTF-8 reader) decodes this file fine — only a locale-dependent read was
    # broken, matching what the real GDACS feed sends.
    return (SAMPLES / name).read_text(encoding="utf-8")


def _raise(*_a: object) -> object:
    raise RuntimeError("stubbed source failure")


# --------------------------------------------------------------------------- #
# WeatherAgent — mapping + failure handling
# --------------------------------------------------------------------------- #
class _FakeAdapter:
    def __init__(self, result: AdapterResult) -> None:
        self.result = result
        self.calls: list[dict] = []

    def fetch(self, params: dict) -> AdapterResult:
        self.calls.append(params)
        return self.result


def _ok_data(**over: object) -> dict:
    d = {
        "wind_speed_kmh": 13.9,
        "wave_height_m": 1.26,
        "visibility_m": 18760.0,
        "precipitation_mm": 0.0,
        "data_time_epoch": 1788264000,
        "active_alerts": [],
        "alerts_source_available": True,
    }
    d.update(over)
    return d


def _ok(data: dict | None = None, status: str = "ok") -> AdapterResult:
    return AdapterResult(data, datetime(2026, 9, 1, tzinfo=UTC), status)


def test_ok_maps_adapter_data_to_weather_result() -> None:
    agent = WeatherAgent(_FakeAdapter(_ok(_ok_data())))
    r = agent.get_conditions(LatLon(9.93, 76.26))
    assert r.status == "ok"
    assert r.wind_speed_kmh == 13.9
    assert r.wave_height_m == 1.26
    assert r.data_timestamp == datetime.fromtimestamp(1788264000, tz=UTC)  # FR-WX-3


def test_adapter_unavailable_gives_unavailable_result_no_fabrication() -> None:
    # FR-WX-4 / NFR-REL-1: explicit unavailable, no invented numbers.
    agent = WeatherAgent(_FakeAdapter(_ok(None, status="unavailable")))
    r = agent.get_conditions(LatLon(9.93, 76.26))
    assert r.status == "unavailable"
    assert r.wind_speed_kmh == 0.0
    assert r.wave_height_m == 0.0
    assert r.active_alerts == []
    assert r.data_timestamp is None


def test_stale_status_is_treated_as_unavailable_by_agent() -> None:
    agent = WeatherAgent(_FakeAdapter(_ok(_ok_data(), status="stale")))
    assert agent.get_conditions(LatLon(9.93, 76.26)).status == "unavailable"


def test_missing_epoch_falls_back_to_fetched_at() -> None:
    fetched = datetime(2026, 9, 1, 12, 0, tzinfo=UTC)
    result = AdapterResult(_ok_data(data_time_epoch=None), fetched, "ok")
    agent = WeatherAgent(_FakeAdapter(result))
    assert agent.get_conditions(LatLon(9.93, 76.26)).data_timestamp == fetched


def test_active_alerts_passed_through_verbatim() -> None:
    alerts = ["Cyclonic Storm warning (Severe)", "Tropical cyclone MARIE (Green) — ~800 km away"]
    agent = WeatherAgent(_FakeAdapter(_ok(_ok_data(active_alerts=alerts))))
    assert agent.get_conditions(LatLon(13.08, 80.27)).active_alerts == alerts  # FR-WX-2


def test_alerts_source_unavailable_flag_maps_through_to_weatherresult() -> None:
    # NFR-REL-1: forecast is fine but the alert feeds were unreachable -> the
    # WeatherResult must say so, not imply "no alerts". (Synthesis wording +
    # Risk INSUFFICIENT_DATA handling of this flag are P2 #37 / P4 #33.)
    agent = WeatherAgent(
        _FakeAdapter(_ok(_ok_data(active_alerts=[], alerts_source_available=False)))
    )
    r = agent.get_conditions(LatLon(13.08, 80.27))
    assert r.status == "ok"
    assert r.alerts_source_available is False
    assert r.active_alerts == []


def test_window_defaults_to_none_and_location_is_forwarded() -> None:
    fake = _FakeAdapter(_ok(_ok_data()))
    WeatherAgent(fake).get_conditions(LatLon(8.88, 76.60))
    assert fake.calls[0]["window"] is None
    assert fake.calls[0]["lat"] == 8.88
    assert fake.calls[0]["lon"] == 76.60


@pytest.mark.parametrize(
    "loc", [LatLon(9.93, 76.26), LatLon(13.08, 80.27), LatLon(8.88, 76.60)]
)
def test_returns_weatherresult_for_three_locations(loc: LatLon) -> None:
    agent = WeatherAgent(_FakeAdapter(_ok(_ok_data())))
    r = agent.get_conditions(loc)
    assert r.status == "ok"
    assert r.wind_speed_kmh > 0
    assert r.data_timestamp is not None


# --------------------------------------------------------------------------- #
# WeatherDataAdapter — pure helpers against captured samples
# --------------------------------------------------------------------------- #
def test_normalise_from_captured_open_meteo_samples() -> None:
    fc = _json("openmeteo_forecast_kochi.json")
    mar = _json("openmeteo_marine_kochi.json")
    data = _normalise(fc, mar, wapi_alerts=[], gdacs_alerts=[])
    assert data is not None
    assert data["wind_speed_kmh"] == fc["current"]["wind_speed_10m"]
    assert data["wave_height_m"] == mar["current"]["wave_height"]
    assert data["visibility_m"] == fc["current"]["visibility"]
    assert isinstance(data["data_time_epoch"], int)
    assert data["active_alerts"] == []
    assert data["alerts_source_available"] is True


def test_normalise_returns_none_when_core_field_missing() -> None:
    fc = _json("openmeteo_forecast_kochi.json")
    assert _normalise(fc, {"current": {"wave_period": 10.0}}, [], []) is None  # no wave_height
    mar = _json("openmeteo_marine_kochi.json")
    assert _normalise({"current": {"precipitation": 0.0}}, mar, [], []) is None  # no wind


def test_normalise_alerts_source_unavailable_when_both_none() -> None:
    data = _normalise(
        _json("openmeteo_forecast_kochi.json"),
        _json("openmeteo_marine_kochi.json"),
        wapi_alerts=None,
        gdacs_alerts=None,
    )
    assert data is not None
    assert data["alerts_source_available"] is False
    assert data["active_alerts"] == []


def test_normalise_accepts_iso_time_string() -> None:
    fc = {"current": {"wind_speed_10m": 12.0, "time": "2026-09-01T14:45"}}
    mar = {"current": {"wave_height": 1.0, "time": "2026-09-01T14:45"}}
    data = _normalise(fc, mar, [], [])
    assert data is not None
    assert isinstance(data["data_time_epoch"], int)


def test_alert_strings_merges_weatherapi_then_gdacs() -> None:
    wapi = [{"headline": "Cyclone warning", "severity": "Severe"}, {"event": "High Wave"}]
    gdacs = [{"headline": "Tropical cyclone BIPARJOY (Orange)", "distance_km": 640.0}]
    assert _alert_strings(wapi, gdacs) == [
        "Cyclone warning (Severe)",
        "High Wave",
        "Tropical cyclone BIPARJOY (Orange) — ~640.0 km away",
    ]
    assert _alert_strings(None, None) == []


def test_parse_gdacs_tc_filters_by_distance() -> None:
    xml = _text("gdacs_tc_rss.xml")
    root = ET.fromstring(xml)
    first_tc = next(
        it
        for it in root.iterfind(".//item")
        if it.findtext("gdacs:eventtype", default="", namespaces=_GDACS_NS) == "TC"
    )
    tc_lat, tc_lon = (float(v) for v in _gdacs_item_latlon(first_tc))

    near = _parse_gdacs_tc(xml, tc_lat, tc_lon)
    assert len(near) >= 1
    assert near[0]["event"] == "Tropical Cyclone"
    assert near[0]["distance_km"] < 1200.0
    assert near[0]["name"]  # eventname populated

    far = _parse_gdacs_tc(xml, -tc_lat, tc_lon + 179.0)
    assert far == []


def test_parse_gdacs_tc_bad_xml_raises_rather_than_claiming_no_cyclones() -> None:
    """#147 — this test used to assert `== []`, which was the bug.

    _normalise() reads None as "alert source not checked" and [] as "checked,
    nothing active". Returning [] for a feed we could not parse reported an
    unreadable cyclone feed as "no cyclones nearby": it could silently drop a
    live TC alert, and — if WeatherAPI was also down — make
    alerts_source_available claim both sources were checked when neither was.

    Raising lets _safe() turn it into None, which is what "we don't know"
    means here (NFR-REL-2)."""
    with pytest.raises(ET.ParseError):
        _parse_gdacs_tc("<not-xml", 9.9, 76.3)


def test_an_unparseable_feed_leaves_the_alert_source_unchecked() -> None:
    """The consequence that matters, asserted end-to-end through _normalise:
    a broken GDACS feed must not be able to pass off "no alerts" as checked."""
    normalised = _normalise(
        {"current": {"wind_speed_10m": 10.0, "time": 1788264000}},
        {"current": {"wave_height": 0.5, "time": 1788264000}},
        None,  # WeatherAPI unavailable too
        None,  # what _safe() hands us for an unparseable GDACS feed
        "open-meteo",
    )

    assert normalised["alerts_source_available"] is False
    assert normalised["active_alerts"] == []  # empty, but flagged as UNKNOWN above


# --------------------------------------------------------------------------- #
# WeatherDataAdapter.fetch — orchestration via monkeypatched fetchers
# --------------------------------------------------------------------------- #
@pytest.fixture()
def adapter() -> WeatherDataAdapter:
    return WeatherDataAdapter()


def _stub_sources(
    monkeypatch: pytest.MonkeyPatch,
    ad: WeatherDataAdapter,
    *,
    forecast: object,
    marine: object,
    wapi: object = None,
    gdacs: object = (),
) -> None:
    def _fn(val: object):
        return (lambda _la, _lo: _raise()) if val is _raise else (lambda _la, _lo: val)

    def _wapi_payload(val: object):
        """_fetch_weatherapi returns the whole forecast.json payload (#116), but
        these tests care about the alerts leg, so a list is wrapped into the
        payload shape here. None still means "couldn't check at all"."""
        if val is _raise or val is None:
            return val
        return {"alerts": {"alert": val}}

    monkeypatch.setattr(ad, "_fetch_forecast", _fn(forecast))
    monkeypatch.setattr(ad, "_fetch_marine", _fn(marine))
    monkeypatch.setattr(ad, "_fetch_weatherapi", _fn(_wapi_payload(wapi)))
    monkeypatch.setattr(ad, "_fetch_gdacs_tc", _fn([] if gdacs == () else gdacs))


def test_fetch_ok_when_all_sources_stubbed(
    adapter: WeatherDataAdapter, monkeypatch: pytest.MonkeyPatch
) -> None:
    fc = _json("openmeteo_forecast_chennai.json")
    _stub_sources(
        monkeypatch, adapter, forecast=fc, marine=_json("openmeteo_marine_chennai.json"), wapi=[]
    )
    res = adapter.fetch({"lat": 13.08, "lon": 80.27, "window": None})
    assert res.status == "ok"
    assert res.data["wind_speed_kmh"] == fc["current"]["wind_speed_10m"]
    assert res.data["alerts_source_available"] is True


def test_fetch_unavailable_when_forecast_raises(
    adapter: WeatherDataAdapter, monkeypatch: pytest.MonkeyPatch
) -> None:
    # FR-WX-4 + LLD §2.9: adapter degrades, never raises.
    _stub_sources(
        monkeypatch, adapter, forecast=_raise, marine=_json("openmeteo_marine_kochi.json"), wapi=[]
    )
    res = adapter.fetch({"lat": 9.93, "lon": 76.26, "window": None})
    assert res.status == "unavailable"
    assert res.data is None


def test_fetch_unavailable_when_marine_raises(
    adapter: WeatherDataAdapter, monkeypatch: pytest.MonkeyPatch
) -> None:
    _stub_sources(
        monkeypatch, adapter, forecast=_json("openmeteo_forecast_kochi.json"), marine=_raise
    )
    res = adapter.fetch({"lat": 9.93, "lon": 76.26, "window": None})
    assert res.status == "unavailable"
    assert res.data is None


def test_fetch_ok_but_alerts_unavailable_when_both_alert_sources_fail(
    adapter: WeatherDataAdapter, monkeypatch: pytest.MonkeyPatch
) -> None:
    _stub_sources(
        monkeypatch,
        adapter,
        forecast=_json("openmeteo_forecast_kochi.json"),
        marine=_json("openmeteo_marine_kochi.json"),
        wapi=_raise,
        gdacs=_raise,
    )
    res = adapter.fetch({"lat": 9.93, "lon": 76.26, "window": None})
    assert res.status == "ok"
    assert res.data["alerts_source_available"] is False
    assert res.data["active_alerts"] == []


@pytest.mark.parametrize("bad", [{}, {"lat": "x", "lon": 1}, {"lat": None, "lon": None}])
def test_fetch_bad_params_is_unavailable_not_raise(
    adapter: WeatherDataAdapter, bad: dict
) -> None:
    res = adapter.fetch(bad)
    assert res.status == "unavailable"
    assert res.data is None


def test_agent_over_adapter_end_to_end_stubbed(monkeypatch: pytest.MonkeyPatch) -> None:
    ad = WeatherDataAdapter()
    _stub_sources(
        monkeypatch,
        ad,
        forecast=_json("openmeteo_forecast_kollam.json"),
        marine=_json("openmeteo_marine_kollam.json"),
        wapi=None,
    )
    r = WeatherAgent(ad).get_conditions(LatLon(8.88, 76.60))
    assert r.status == "ok"
    assert r.wind_speed_kmh > 0
    assert r.wave_height_m >= 0
    assert r.data_timestamp is not None
    assert r.data_timestamp.tzinfo is not None


# --------------------------------------------------------------------------- #
# #147 — the GDACS feed is global and 1.5 MB; fetching it per query was both
# the bulk of this leg's latency and the whole of our exposure to a transient
# unreadable response.
# --------------------------------------------------------------------------- #


def _gdacs_rss(event_lat: float = 9.9, event_lon: float = 76.3) -> str:
    return f"""<rss xmlns:gdacs="http://www.gdacs.org"
                    xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#">
      <channel><item>
        <gdacs:eventtype>TC</gdacs:eventtype>
        <gdacs:eventname>TestCyclone</gdacs:eventname>
        <gdacs:alertlevel>Orange</gdacs:alertlevel>
        <geo:Point><geo:lat>{event_lat}</geo:lat><geo:long>{event_lon}</geo:long></geo:Point>
      </item></channel>
    </rss>"""


def test_the_global_feed_is_fetched_once_and_reused(
    adapter: WeatherDataAdapter, monkeypatch: pytest.MonkeyPatch
) -> None:
    """One entry serves every location — only the radius filter is per query."""
    calls = {"n": 0}

    def _fake_get(source, url, **kwargs):
        calls["n"] += 1
        return httpx.Response(200, text=_gdacs_rss(), request=httpx.Request("GET", url))

    monkeypatch.setattr(wa, "_get", _fake_get)

    near = adapter._fetch_gdacs_tc(9.9, 76.3)
    far = adapter._fetch_gdacs_tc(-40.0, 10.0)  # different location, same feed

    assert calls["n"] == 1
    assert near and not far  # filtered per query, not served from one another


def test_an_unparseable_feed_is_not_cached(
    adapter: WeatherDataAdapter, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Storing before parsing would pin a broken feed for the whole TTL, so a
    transient bad response would keep every later query from seeing cyclones."""
    bodies = ["<not-xml", _gdacs_rss()]

    def _fake_get(source, url, **kwargs):
        return httpx.Response(200, text=bodies.pop(0), request=httpx.Request("GET", url))

    monkeypatch.setattr(wa, "_get", _fake_get)

    with pytest.raises(ET.ParseError):
        adapter._fetch_gdacs_tc(9.9, 76.3)

    # The retry refetches instead of replaying the broken body.
    assert adapter._fetch_gdacs_tc(9.9, 76.3)
